"""empty message

Revision ID: 14dbae72ec3
Revises: None
Create Date: 2015-05-07 08:38:18.383085

"""

# revision identifiers, used by Alembic.
revision = '14dbae72ec3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128))
    op.add_column('menuitems', sa.Column('bonus', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menuitems', 'bonus')
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
