"""empty message

Revision ID: 209c6a0ad103
Revises: 14dbae72ec3
Create Date: 2015-05-07 09:10:53.232804

"""

# revision identifiers, used by Alembic.
revision = '209c6a0ad103'
down_revision = '14dbae72ec3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
