"""empty message

Revision ID: 33f3f6783a08
Revises: None
Create Date: 2015-05-03 14:52:21.853590

"""

# revision identifiers, used by Alembic.
revision = '33f3f6783a08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
