"""empty message

Revision ID: ef2fcea8f78
Revises: 209c6a0ad103
Create Date: 2015-05-07 13:04:22.073279

"""

# revision identifiers, used by Alembic.
revision = 'ef2fcea8f78'
down_revision = '209c6a0ad103'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128))
    op.add_column('orders', sa.Column('bonus_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'bonus_price')
    op.alter_column('city', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
