"""empty message

Revision ID: 435c5ddb8911
Revises: None
Create Date: 2015-05-06 12:36:15.924950

"""

# revision identifiers, used by Alembic.
revision = '435c5ddb8911'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
