"""empty message

Revision ID: 4a7a51a7cc99
Revises: 435c5ddb8911
Create Date: 2015-05-06 12:43:51.663245

"""

# revision identifiers, used by Alembic.
revision = '4a7a51a7cc99'
down_revision = '435c5ddb8911'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
